// Mocks generated by Mockito 5.3.2 from annotations
// in zac/test/helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zac/src/zac/context.dart' as _i5;
import 'package:zac/src/zac/transformers.dart' as _i3;

import 'helper.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TestTransformExecute].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestTransformExecute extends _i1.Mock
    implements _i2.TestTransformExecute {
  MockTestTransformExecute() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Object? call(
    _i3.ZacTransformValue? transformValue,
    _i4.BuildContext? context,
    _i5.ZacContext? zacContext,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #call,
        [
          transformValue,
          context,
          zacContext,
        ],
      )) as Object?);
}

/// A class which mocks [TestActionExecute].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestActionExecute extends _i1.Mock implements _i2.TestActionExecute {
  MockTestActionExecute() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(
    _i4.BuildContext? context,
    _i5.ZacContext? zacContext,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #call,
          [
            context,
            zacContext,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
