name: zac_template_expressions
description: Zac Transformer for package "template_expressions"
version: 0.0.1
homepage: https://github.com/smiLLe/zac

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  template_expressions: ^1.1.6+2
  zac:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  json_serializable: ^6.1.3
  build_runner:
  mockito: ^5.1.0

flutter: