name: zac
description: Dynamically create Widgets based on JSON
version: 0.1.0-dev.3
homepage: https://github.com/smiLLe/zac

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  flutter_hooks: ^0.18.5+1
  riverpod: ^2.0.0-dev.9
  hooks_riverpod: ^2.0.0-dev.9
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ">=4.2.0 <5.0.0"
  flutter_lints: ^1.0.0
  freezed: ^2.0.3+1
  json_serializable: ^6.1.3
  build_runner:
  mockito: ^5.1.0


flutter: