name: zac_template_expressions
description: Zac Builders/Transformer for package "template_expressions"
version: 0.1.0-dev.4
homepage: https://github.com/smiLLe/zac/tree/main/zac/packages/zac_template_expressions
repository: https://github.com/smiLLe/zac/tree/main/zac/packages/zac_template_expressions

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  template_expressions: ^1.1.6+2
  json_annotation: ^4.6.0
  zac: 0.1.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  json_serializable: ^6.3.2
  build_runner: ^2.2.0
  mockito: ^5.1.0

flutter: